# Generated by Django 5.2.10 on 2026-02-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_report_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='scan_type',
            field=models.CharField(choices=[('standard', 'Standard Analysis'), ('deep', 'Deep Forensic Scan')], default='standard', max_length=20),
        ),
    ]
