# Generated by Django 5.2.10 on 2026-02-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_scan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='file_path',
            field=models.CharField(blank=True, default='N/A', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='line_number',
            field=models.CharField(blank=True, default='N/A', max_length=50, null=True),
        ),
    ]
